### ISSUE TITLE
To defend Meltdown-style attack

### ISSUE THREAD

**Issue by pluviophilee** [SamAinsworth/reproduce-ghostminion-paper#1]
Hi,

I have already read your paper. Your work is impressive. However, I have few questions. I see your code and find that GhostMinion calls function ghostClear() to evict all entries in GM, while dealing with a mispredicted branch on the commit stage. But, the malicious entry will be kept in GM when it was brought by a fault(like TSX fault in Meltdown) without evict. And, the attacker may recover the secrets by reloading the same entry and measuring the execution cycles. My question is, is the GhostMinion able to defend Meltdown-style attacks?

**Comment by SamAinsworth** [comment]
Hi Pluviophilee,

Sometimes the code is a bit approximate -- really, the code ought to clear the ghostMinion on any exceptional behaviour -- I'm not sure if there are other paths in gem5 where it restarts execution though?

Separately, Meltdown shouldn't be possible to trigger in gem5, as it shouldn't speculate over the detected exception -- and Meltdown is trivial to defend against in real processors by not forwarding data when access rights in the TLB don't match. So yes, GhostMinion is able to defend against any Meltdown-style attacks, but there are much easier methods of doing so.

**Comment by pluviophilee** [comment]
Ok, I got it. Thanks for replying. ^ ^
